theme: minima
title: Grzegorz Czernatowicz | Gecko Code - Technical Radical Blog
author:
   name: Grzegorz Czernatowicz
   email: gczernatowicz@geckocode.pl

description: [Github](https://github.com/Random90) Writing about programming and tech and other interesting things and problems I encounter while working on my projects like Gecko Budget Android app.

minima:
  skin: auto
  show_excerpts: true
  social_links:
       - title: My GitHub profile
         icon: github
         url: "https://github.com/Random90"
  hide_site_feed_link: false


